version: "3.8"
services:
  sui:
    container_name: sui
    image: pyunramura/sui:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      - VIRTUAL_HOST=example.com
    ports:
      - 4000:8080
    volumes:
      - ./:/opt/html
